apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-hello
  template:
    metadata:
      labels:
        app: java-hello
    spec:
      containers:
      - name: java-hello
        image: glacierknight/java-hello:latest